//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lands.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lands.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha Code 2:.
        /// </summary>
        public static string AlphaCode2 {
            get {
                return ResourceManager.GetString("AlphaCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha Code 3:.
        /// </summary>
        public static string AlphaCode3 {
            get {
                return ResourceManager.GetString("AlphaCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area:.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borders.
        /// </summary>
        public static string Borders {
            get {
                return ResourceManager.GetString("Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brazilian:.
        /// </summary>
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capital:.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIOC:.
        /// </summary>
        public static string CIOC {
            get {
                return ResourceManager.GetString("CIOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Croatian:.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demonym:.
        /// </summary>
        public static string Demonym {
            get {
                return ResourceManager.GetString("Demonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dutch:.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter an email..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French:.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a German:.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GINI:.
        /// </summary>
        public static string GINI {
            get {
                return ResourceManager.GetString("GINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Italian:.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japanese:.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages.
        /// </summary>
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Native Name:.
        /// </summary>
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numeric Code:.
        /// </summary>
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a password..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persian:.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Population:.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portuguese:.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region:.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rememberme in this device.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something was wrong, please try later..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish:.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statics.
        /// </summary>
        public static string Statics {
            get {
                return ResourceManager.GetString("Statics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subregion:.
        /// </summary>
        public static string Subregion {
            get {
                return ResourceManager.GetString("Subregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
    }
}
